version: "3.7"

services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dogmatiq
      MYSQL_USER: dogmatiq
      MYSQL_PASSWORD: dogmatiq
    ports:
    - "3306:3306/tcp"
    volumes:
    - mariadb:/var/lib/mysql
  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: rootpass
    ports:
    - "5432:5432/tcp"
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  mariadb:
  postgres:
